dist: xenial
sudo: enabled
language: perl
perl:
- '5.26'
- '5.24'
- '5.22'
env:
  global:
    secure: Cc6eQhbhCDa+0kzSxTmkh8Xx1SecDLUmd1g7WPPEuyfAgRhNaO/kMF9RBFtp6/D71MK4PejZHQ0oQAVOeTPWSKTkGEFEgpkcoJbr/2DnIo34fbzw7AKSPyKDKrAXHtGqCrL/tKgdfq31xe3bl0T1XYEN1FSKjJtHJHCAW26DqzoXvinKd3V09AqYAZTRvTLeWbcF74xYKWcwTSC5RLkCyuEAjfGdogTdmf4Dh4+OQOgLB518ZOz5peXhro5iTFLa1FgUL5JzNhYx0lpScW6M/0zw+j4wGG5K2osQCHTPtwFGeosICBJKVm6vvq56ANyPonioboWLYGxIzntlxnywlz/3MA6Ie4rFklaaOI5ksJ3ICMedN35OmslrrrHsE1vu9jU+8I8R4RxNyvKF/iFGhn9fI8uTWN0+sf2LPywhAw462eXurE96tp+tHCrSKS2qj/0sKhBE0d4kYUWI4jI8zaFLufzub+NmFCA+GAuqgXpvfzovRo9g6Ag/AL/erMRBe4EVrAlqNfHdlJjBfdpw3ZgKun6yqtI1aS51rVCnRy1DIYZC0qkbmT5I3GyYGUM0EAfvjknxlpMvnhik+rcE/GcZ4GU21rovyrsFj4Wbu4e+7Ia8oXwDfAARlQXKbH9zZGsv8WBTDnTdCFVyxkzt2unPtilwSBXpuN3PDaENLKY=
cache:
  directories:
  - "$HOME/perl5"
git:
  depth: false
before_install:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git config --global push.default simple
- git remote set-url origin https://${GH_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
- wget -qO - http://debian.fhem.de/archive.key | sudo apt-key add -
- echo "deb http://debian.fhem.de/nightly/ /" | sudo tee -a /etc/apt/sources.list
install:
- sudo apt-get update -qq
- cpanm File::Find File::Basename Mock::Sub Test::More Test::Device::SerialPort JSON
  --notest
- sudo apt-get install fhem -qq -y
- sudo chown travis -R /opt/fhem
script:
- make test -j2
- make fhem_kill
- "./build_controls_list.sh"
- git commit -m "Travis automatic update controls file. Build (${TRAVIS_BUILD_NUMBER})
  [skip ci]" ./controls_unittest.txt || true
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ $TRAVIS_JOB_NUMBER == *.1 ]]; then
  git push origin HEAD:$TRAVIS_BRANCH ; fi
