requires 'Test2::Suite';
requires 'File::Find';
requires 'File::Basename'; 
requires 'Mock::Sub'; 
requires 'Test::More';
requires 'Test::Device::SerialPort';
requires 'Devel::Cover';
requires 'Devel::Cover::Report::Clover';
requires 'JSON';